main/urls.py
from django.urls import path
from .views import MainHome, PostView, PostAdd

app_name = 'main'
urlpatterns = [
    path('', MainHome.as_view(), name='home'),
    path('posts/<slug:slug>/', PostView.as_view(), name='post_detail'),
    path('add_post/', PostAdd.as_view(), name='post_add'),
]

no_AI_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('users.urls')),
]

users/urls.py
from django.urls import path

from users.views import RegisterView, CustomUserLoginView, EmailConfirmView

app_name = 'users'
urlpatterns = [
    path('create_account/', RegisterView.as_view(), name='register'),
    path('login/', CustomUserLoginView.as_view(), name='login'),
    path('create_account/email_confirm/', EmailConfirmView.as_view(), name='email_confirm')
]

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import BooleanField, EmailField, CharField, ForeignKey, SET_NULL, DateTimeField


class CustomUserManager(BaseUserManager):

    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('У пользователя должен быть email')
        if not username:
            raise ValueError('У пользователя должен быть username')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractUser):

    email = EmailField(unique=True)
    username = CharField(unique=True, max_length=30)
    email_confirmed = BooleanField(default=False)

    REQUIRED_FIELDS = ['username']
    USERNAME_FIELD = 'email'

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.username or 'Нет имени'} — {self.email}"

class EmailCodeVerification(models.Model):

    user = ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='email_codes')
    is_used = BooleanField(default=False)
    code = CharField(max_length=6)
    create_time = DateTimeField(auto_now_add=True)
    end_time = DateTimeField()

users/forms.py
from django.contrib.auth import authenticate, login
from django.core.validators import RegexValidator

from .models import CustomUser
from django import forms

class RegisterForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'password']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Указанный адрес электронной почты уже занят')
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if CustomUser.objects.filter(username=username).exists():
            raise forms.ValidationError('Указанное имя пользователя уже занято')
        return username

    def clean(self):

        cleaned = super().clean()
        p1 = cleaned.get('password')
        p2 = cleaned.get('password1')

        if p1 != p2:
            raise forms.ValidationError('Введеные пароли не совпадают.')

        return cleaned

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password')
        if password:
            user.set_password(password)
        user.is_active = False
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):

        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        user = authenticate(request=self.request, email=email, password=password)
        if user is None:
            raise forms.ValidationError("Неверный адрес электронной почты или пароль.")
        if not user.is_active:
            raise forms.ValidationError("Аккаунт не прошёл активацию, проверьте ваш почтовый ящик.")
        self.user = user

        return cleaned_data

    def get_user(self):
        return self.user

class EmailConfirmForm(forms.Form):

    code = forms.CharField(max_length=6,
                           validators=[
                               RegexValidator(r'^\d{6}$', 'Код должен содержать ровно 6 цифр.')
                           ])

users/views.py
from Scripts.bottle import request
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, FormView

from users.forms import RegisterForm, LoginForm, EmailConfirmForm
from users.models import CustomUser, EmailCodeVerification
from .services.send_email_code import send_code


class RegisterView(CreateView):

    model = CustomUser
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:email_confirm')

    def form_valid(self, form):
        response = super().form_valid(form)
        send_code(self.object)
        self.request.session["verify_user_id"] = self.object.id
        return response

class CustomUserLoginView(LoginView):

    form_class = LoginForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('main:home')
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('main:home')

class EmailConfirmView(FormView):

    template_name = 'users/email_confirm.html'
    form_class = EmailConfirmForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):

        user_id = self.request.session.get("verify_user_id")
        code = form.cleaned_data['code']
        if not user_id:
            form.add_error(None, "Ошибка: пользователь не найден в сессии")
            return self.form_invalid(form)

        user = CustomUser.objects.get(id=user_id)

        try:
            obj = EmailCodeVerification.objects.filter(
                user=user,
                code=code
            ).latest("create_time")

        except EmailCodeVerification.DoesNotExist:
            form.add_error("code", "Неверный код подтверждения")
            return self.form_invalid(form)

        if timezone.now() > obj.end_time:
            form.add_error('Срок действия кода истек')
            return self.form_invalid(form)

        if obj.is_used:
            form.add_error('Указанный код не действителен')
            return self.form_invalid(form)

        user.is_active = True
        user.email_confirmed = True
        user.save()

        obj.is_used = True
        obj.save()

        try:
            del self.request.session['verify_user_id']
        except KeyError:
            pass

        messages.success(self.request, "Почта успешно подтверждена!")
        return super().form_valid(form)

users/templates/users/email_confirm.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="form-container">
    <h2 class="form-title">Подтверждение email</h2>

    <p style="text-align:center; margin-bottom: 20px;">
        Мы отправили шестизначный код подтверждения на вашу почту.
    </p>

    <form method="post" id="code-form">
        {% csrf_token %}

        <div class="code-input-wrapper">
            {% for i in "123456" %}
            <input type="text"
                   maxlength="1"
                   class="code-box"
                   inputmode="numeric"
                   pattern="\d*"
                   required>
            {% endfor %}
        </div>

        <input type="hidden" name="code" id="real-code">

        {% if form.errors %}
            <p class="error-text">
                {{ form.errors.code.0 }}
            </p>
        {% endif %}

        <button type="submit" class="form-btn" style="width: 100%; margin-top: 25px;">
            Подтвердить
        </button>

        <div class="resend-wrapper">
            <button type="button" id="resend-btn" class="resend-btn">
                Отправить код повторно
            </button>
            <span id="timer"></span>
        </div>
    </form>
</div>
<script src="{% static 'users/email_confirm.js' %}"></script>
{%endblock%}

users/templates/users/email_confrim.html
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form }}
</form>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}

{% block title %}Вход / Хохл{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">Вход в аккаунт</h2>

    <form method="post">
        {% csrf_token %}

        <label for="id_email">Адрес электронной почты</label>
        {{ form.email }}

        <label for="id_password">Пароль</label>
        {{ form.password }}

        <button class="form-btn" type="submit">Войти</button>
    </form>

    <p style="margin-top: 15px;">
        Нет аккаунта?
        <a href="{% url 'users:register' %}">Зарегистрироваться</a>
    </p>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}

{% block title %}Регистрация / Хохл{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">Регистрация</h2>

    <form method="post">
        {% csrf_token %}

        <label for="id_email">Адрес электронной почты</label>
        {{ form.email }}

        <label for="id_username">Имя пользователя</label>
        {{ form.username }}

        <label for="id_password">Пароль</label>
        {{ form.password }}

        <label for="id_password1">Повторите пароль</label>
        {{ form.password1 }}

        <button class="form-btn" type="submit">Создать аккаунт</button>
    </form>

    <p style="margin-top: 15px;">
        Уже есть аккаунт?
        <a href="{% url 'users:login' %}">Войти</a>
    </p>
</div>
{% endblock %}