main/urls.py
from django.urls import path
from .views import MainHome, PostView, PostAdd

app_name = 'main'
urlpatterns = [
    path('', MainHome.as_view(), name='home'),
    path('posts/<slug:slug>/', PostView.as_view(), name='post_detail'),
    path('add_post/', PostAdd.as_view(), name='post_add'),
]

no_AI_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('users.urls')),
]

main/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Post(models.Model):

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, blank=True, null=True, verbose_name='Автор')
    title = models.CharField(max_length=50, verbose_name="Заголовок")
    slug = models.SlugField(unique=True, verbose_name="Слаг")
    text_content = models.TextField(verbose_name='Содержание статьи')
    is_published = models.BooleanField(default=True, verbose_name="Опубликовать")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    image = models.ImageField(blank=True, null=True, verbose_name="Изображение")
    categories = models.ManyToManyField(Category, blank=True, related_name='posts', verbose_name="Категория")

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(**kwargs)

    def categories_list(self):
        return ", ".join(c.name for c in self.categories.all())

main/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'categories', 'text_content', 'image', 'is_published']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'categories': forms.SelectMultiple(attrs={'class': 'form-select'}),
            "text_content": forms.Textarea(attrs={'class': 'form-text','rows': 20, }),
            'image': forms.FileInput(attrs={'class': 'form-file'}),
            'is_published': forms.CheckboxInput(attrs={'class': 'form-check'}),
        }

        labels = {
            'title': "Заголовок",
            "categories": "Категории",
            "text_content": "Содержание статьи",
            "image": "Изображение",
            "is_published": "Опубликовать сразу",
        }

main/views.py
from Scripts.bottle import request
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.transaction import commit
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy

from .models import Category, Post
from .forms import PostForm
from django.views.generic import ListView, DetailView, FormView, CreateView


class MainHome(ListView):

    model = Post
    template_name = 'main/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(is_published=True)

class PostView(DetailView):

    model = Post
    template_name = 'main/posts.html'
    context_object_name = 'post'

class PostAdd(LoginRequiredMixin, CreateView):

    model = Post
    form_class = PostForm
    template_name = 'main/post_add.html'
    success_url = reverse_lazy('main:home')
    login_url = reverse_lazy('users:register')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

main/templates/main/index.html
{%extends 'main.html'%}
{% block title %}
Главная страница / Хохл
{% endblock %}

{% block content %}
<div class="posts-container">
<ul class="posts-list">
{% for post in posts %}
    {% if post.is_published %}
       <li class="post-item"><h3>{{ post.title }}</h3> <p>Категории: {{ post.categories_list }}</p>
       <p>{{post.text_content|truncatechars:500}}</p>
       <a class='read-btn' href="{% url 'main:post_detail' post.slug %}">Читать статью</a>
       </li>
    {% endif %}
{% endfor %}
</ul>
</div>
{% endblock %}

main/templates/main/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
</head>
<body>

<header>
    <nav class="navbar">
        <div class="nav-left">
            <a href="{% url 'main:home' %}">Главная</a>
        </div>

        <div class="nav-right">
            <a href="{% url 'main:post_add' %}">Опубликовать статью</a>
            <a href="#">Войти</a>
        </div>
    </nav>
</header>
{% block content %}
{% endblock %}
</body>
</html>

main/templates/main/post_add.html
{% extends 'main.html' %}
{% block title %} Создание статьи / Хохл {% endblock %}

{% block content %}
<div class="post-container">
<h1>Публикация статьи</h1>

<form method="post" enctype="multipart/form-data"
      class="form-container">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="form-btn">Опубликовать</button>
</form>
</div>

{% endblock %}

main/templates/main/posts.html
{% extends 'main.html' %}

{% block title %}Статьи / Хохл {% endblock %}

{% block content %}
<div class="post-container">
    <p>Автор: {{ post.author }}</p>
<h1>{{ post.title }}</h1>
<p>{{post.text_content|linebreaks}}</p>
</div>
{% endblock %}